Models/DomainModels/PatientRegistration.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;                      // for Remote attribute

namespace SububanMedicalGroupSMGWebApp.Models.DomainModels
{
    public class PatientRegistration
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter your first name.")]
        public string FirstName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter your last name.")]
        public string LastName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a username.")]
        [RegularExpression("^[a-zA-Z ]+$")]
        public string Username { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter an email address.")]
        [Remote("CheckEmail", "Validation")]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a date of birth.")]
        [Age(150, ErrorMessage = "DOB must be a past date and no more than 150 years past.")]
        public DateTime? DOB { get; set; }

        [RegularExpression(@"^\d{3}[-.]\d{3}[-.]\d{4}$", ErrorMessage = "Please enter a valid phone number(should contain digit and delimiter of “-“ or “.” only)")]
        public string PhoneNumber { get; set; } = string.Empty;

        [RegularExpression("^[a-zA-Z0-9 ]+$", ErrorMessage = "Please enter a valid home address(should contain letters in lower or upper case, digit, space only)")]
        public string HomeAddress { get; set; } = string.Empty;

        [RegularExpression(@"^\d{3}-\d{2}-\d{4}$", ErrorMessage = "Please enter a valid Social Security Number(should contain delimiter of “-“ only)")]
        [Remote("SocialSecurityNumberRemote", "Validation")]
        public string SocialSecurityNumber { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a MedicalInsurance")]
        public string MedicalInsurance { get; set; } = string.Empty;
        public DateTime RegistrationDate { get; set; } = DateTime.Now;
        public PatientStatus Status { get; set; } = PatientStatus.Pending;

    }
    public enum PatientStatus
    {
        Pending,
        Approved,
        Rejected
    }
}

Models/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SububanMedicalGroupSMGWebApp.Models.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Please enter a username.")]
        [StringLength(255)]
        public string Username { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a password.")]
        [StringLength(255)]
        public string Password { get; set; } = string.Empty;

        public string ReturnUrl { get; set; } = string.Empty;

        public bool RememberMe { get; set; }
    }
}

Controllers/PatientRegistrationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Win32;
using SububanMedicalGroupSMGWebApp.Models;
using SububanMedicalGroupSMGWebApp.Models.DataLayer;
using SububanMedicalGroupSMGWebApp.Models.DomainModels;
using SububanMedicalGroupSMGWebApp.Models.ViewModels;

namespace SububanMedicalGroupSMGWebApp.Controllers
{
    public class PatientRegistrationController : Controller
    {
        private SMGWebAppContext context;
        private UserManager<User> _user;
        private SignInManager<User> _signIn;
        public PatientRegistrationController(SMGWebAppContext ctx, UserManager<User> user, SignInManager<User> signIn)
        {
            context = ctx;
            _user = user;
            _signIn = signIn;
        }
        [HttpGet]
        public IActionResult Index() => View();
        
        public IActionResult Login() => View();
        [HttpGet]
        public IActionResult Registration() => View();

        [HttpPost]
        public async Task<IActionResult> Registration(PatientRegistration patientRegistration)
        {
            if (TempData["okEmail"] == null)
            {
                string msg = Check.EmailExists(context, patientRegistration.EmailAddress);
                if (!String.IsNullOrEmpty(msg))
                {
                    ModelState.AddModelError(nameof(patientRegistration.EmailAddress), msg);
                }
            }

            if (ModelState.IsValid)
            {
                string IsdefaultUserId = $"{patientRegistration.FirstName}{patientRegistration.LastName}";
                string IsdefaultPassword = $"{patientRegistration.FirstName}{patientRegistration.LastName}123";
                var USER = new User { UserName = IsdefaultUserId, Email = patientRegistration.EmailAddress };
                var res = await _user.CreateAsync(USER, IsdefaultPassword);
                if (res.Succeeded)
                {
                    await _signIn.SignInAsync(USER, isPersistent: false);
                    context.PatientRegistrations.Add(patientRegistration);
                    context.SaveChanges();
                    TempData["RegitrationSuccessMessage"] = "Your registration has been received. We will assess your application and email you the notification with login ID and temporary password";
                    return RedirectToAction("Registration");
                }
                else
                {
                    foreach (var error in res.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
                return View(patientRegistration);
            }
            else
            {
                return View(patientRegistration);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel login)
        {
            if (ModelState.IsValid)
            {
                var result = await _signIn.PasswordSignInAsync(
                    login.Username, login.Password, isPersistent: login.RememberMe,
                    lockoutOnFailure: false);

                if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(login.ReturnUrl) &&
                        Url.IsLocalUrl(login.ReturnUrl))
                    {
                        return Redirect(login.ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            ModelState.AddModelError("", "Invalid username/password.");
            return View(login);
        }
        public ViewResult AccessDenied()
        {
            return View();
        }
        public IActionResult Welcome() => View();
        [HttpPost]
        public async Task<IActionResult> LogOut()
        {
            await _signIn.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public IActionResult Login(string returnURL = "")
        {
            var login = new LoginViewModel 
            { ReturnUrl = returnURL };
            return View(login);
        }
    }
}

Views/PatientRegistration/AccessDenied.cshtml
@{
    ViewBag.Title = "Access Denied";
}

<h2>Access Denied</h2>

Views/PatientRegistration/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model SububanMedicalGroupSMGWebApp.Models.ViewModels.LoginViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<div class="container mt-5 mb-5 d-flex justify-content-center">
    <div class="card px-1 py-4">
        <form method="post" asp-action="Login" asp-controller="PatientRegistration" asp-route-returnUrl="@Model.ReturnUrl">
            <div class="card-body">
                <h6 class="card-title m-1">Login</h6>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="input-group">
                                <input asp-for="Username" class="form-control" type="text" placeholder="Username" />
                                <span asp-validation-for="Username" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="input-group">
                                <input asp-for="Password" class="form-control" type="password" placeholder="Password" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="input-group">
                                <input asp-for="RememberMe" type="checkbox" class="form-check-inline" />
                                <label>Remember Me</label>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block confirm-button">Login</button>
                <a asp-action="Registration" class="btn btn-primary btn-block confirm-button" asp-controller="PatientRegistration">Register</a>
            </div>
        </form>
    </div>
</div>

<style>
    body {
        background-color: #FFEBEE
    }

    .card {
        width: 400px;
        background-color: #fff;
        border: none;
        border-radius: 12px
    }

    label.radio {
        cursor: pointer;
        width: 100%
    }

        label.radio input {
            position: absolute;
            top: 0;
            left: 0;
            visibility: hidden;
            pointer-events: none
        }

        label.radio span {
            padding: 7px 14px;
            border: 2px solid #eee;
            display: inline-block;
            color: #039be5;
            border-radius: 10px;
            width: 100%;
            height: 48px;
            line-height: 27px
        }

        label.radio input:checked + span {
            border-color: #039BE5;
            background-color: #81D4FA;
            color: #fff;
            border-radius: 9px;
            height: 48px;
            line-height: 27px
        }

    .form-control {
        margin-top: 10px;
        height: 48px;
        border: 2px solid #eee;
        border-radius: 10px
    }

        .form-control:focus {
            box-shadow: none;
            border: 2px solid #039BE5
        }

    .agree-text {
        font-size: 12px
    }

    .terms {
        font-size: 12px;
        text-decoration: none;
        color: #039BE5
    }

    .confirm-button {
        border-radius: 10px
    }

</style>

Views/PatientRegistration/Registration.cshtml
@model SububanMedicalGroupSMGWebApp.Models.DomainModels.PatientRegistration
@{
    ViewBag.Title = "Registration";
}

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/minimum-age.js"></script>

@*    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>*@

}
@if (@TempData["RegitrationSuccessMessage"] != null)
{
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Registration Successfull!</h4>
        <p>@TempData["RegitrationSuccessMessage"]</p>
        <hr>
    </div>
}


<div class="container mb-5 d-flex justify-content-center">
    <div class="card px-1 py-4">
        <form asp-action="Registration" method="post">
            <div class="card-body">
            <h6 class="card-title mb-3">Patient Registration</h6>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                            <!-- <label for="name">Name</label> --> <input asp-for="Username" class="form-control" type="text" placeholder="Name" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                            <!-- <label for="name">Name</label> --> <input asp-for="FirstName" class="form-control" type="text" placeholder="FirstName" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                            <!-- <label for="name">Name</label> --> <input asp-for="LastName" class="form-control" type="text" placeholder="LastName" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                            <div class="input-group"> <input asp-for="EmailAddress" class="form-control" type="text" placeholder="EmailAddress" />
                                <span asp-validation-for="EmailAddress" class="text-danger"></span>
                            </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                            <div class="input-group">
                                <input asp-for="DOB" id="DateDOB" class="form-control" type="date" placeholder="DOB" />
                                <span asp-validation-for="DOB" id="ValidationDOB" class="text-danger"></span>
                            </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                            <div class="input-group">
                                <input asp-for="PhoneNumber" class="form-control" type="text" placeholder="PhoneNumber" />
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                            <div class="input-group">
                                <input asp-for="HomeAddress" class="form-control" type="text" placeholder="HomeAddress" />
                                <span asp-validation-for="HomeAddress" class="text-danger"></span>
                            </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                            <div class="input-group">
                                <input asp-for="SocialSecurityNumber" class="form-control" type="text" placeholder="SocialSecurityNumber" />
                                <span asp-validation-for="SocialSecurityNumber" class="text-danger"></span>
                            </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <div class="input-group">
                            <select class="form-control" name="MedicalInsurance" asp-for="MedicalInsurance" required>
                                <option>Aetna</option>
                                <option>Blue Shield Blue Cross</option>
                                <option>Cigna</option>
                                <option>Corvel</option>
                                <option>First Health </option>
                            </select>
                            <span asp-validation-for="MedicalInsurance" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
                <div class=" d-flex flex-column text-center px-5 mt-3 mb-3"> <small class="agree-text">By Registrating this appointment you agree to the</small> <a href="#" class="terms">Terms & Conditions</a> </div> <button type="submit" class="btn btn-primary btn-block confirm-button">Submit</button>
        </div>
        </form>
    </div>
</div>

<style>
    body {
        background-color: #FFEBEE
    }

    .card {
        width: 400px;
        background-color: #fff;
        border: none;
        border-radius: 12px
    }

    label.radio {
        cursor: pointer;
        width: 100%
    }

        label.radio input {
            position: absolute;
            top: 0;
            left: 0;
            visibility: hidden;
            pointer-events: none
        }

        label.radio span {
            padding: 7px 14px;
            border: 2px solid #eee;
            display: inline-block;
            color: #039be5;
            border-radius: 10px;
            width: 100%;
            height: 48px;
            line-height: 27px
        }

        label.radio input:checked + span {
            border-color: #039BE5;
            background-color: #81D4FA;
            color: #fff;
            border-radius: 9px;
            height: 48px;
            line-height: 27px
        }

    .form-control {
        margin-top: 10px;
        height: 48px;
        border: 2px solid #eee;
        border-radius: 10px
    }

        .form-control:focus {
            box-shadow: none;
            border: 2px solid #039BE5
        }

    .agree-text {
        font-size: 12px
    }

    .terms {
        font-size: 12px;
        text-decoration: none;
        color: #039BE5
    }

    .confirm-button {
        height: 50px;
        border-radius: 10px
    }

</style>




<script type="text/javascript">
    const DateDOB = document.getElementById('DateDOB');
    const ValidationDOB = document.getElementById('ValidationDOB');
    DateDOB.addEventListener('blur', function () {
        const inputDOB = DateDOB.value;
        if (!isDateDOB(inputDOB)) {
            ValidationDOB.textContent = "Please enter a valid date in the past and not more than 150 years ago.";
            ValidationDOB.style.color = 'red';
            DateDOB.focus();
        }
    });
    function isDateDOB(inputDOB) {
        const date = new Date(inputDOB);
        if (isNaN(date.getTime()) || date > new Date() || date < new Date(new Date().getFullYear() - 150, 0, 1)) {
            return false;
        }
        return true;
    }
</script>