Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SububanMedicalGroupSMGWebApp.Models.DataLayer;
using SububanMedicalGroupSMGWebApp.Models.DomainModels;
using SububanMedicalGroupSMGWebApp.Models.ExtensionMethods;
using SububanMedicalGroupSMGWebApp.Models.ViewModels;

namespace SububanMedicalGroupSMGWebApp.Controllers
{
    public class FavoritesController : Controller
    {
        private SMGWebAppContext context;
        public FavoritesController(SMGWebAppContext ctx) => context = ctx;

        [HttpGet]
        public ViewResult Index()
        {
            var session = new SMGSession(HttpContext.Session);
            var model = new SMGViewModel
            {
                ActiveSpecs = session.GetActiveSpecs(),
                ActiveGens = session.GetActiveGens(),
                ActiveTowns = session.GetActiveTowns(),
                Physicians = session.GetMyPhyc()
            };

            return View(model);
        }

        [HttpPost]
        public RedirectToActionResult Add(Physician physician)
        {
            // get full team data from database
            physician = context.Physician
                 .Include(t => t.Specialities)
                 .Include(t => t.Clinic)
                 //.Include(t => t.Gender)
                 .Where(t => t.PhysicianID == physician.PhysicianID)
                 .FirstOrDefault() ?? new Physician();

            // add team to favorite teams in session and cookie
            var session = new SMGSession(HttpContext.Session);
            var cookies = new SMGCookies(Response.Cookies);

            var teams = session.GetMyPhyc();
            teams.Add(physician);
            session.SetMyPhyc(teams);        
            cookies.SetMyPhycIds(teams);

            // set add message
            TempData["message"] = $"{physician.FirstName} added to your favorites";

            // redirect to Home page
            return RedirectToAction("Index", "FindaProvider", 
                new {
                    ActiveSpecialities = session.GetActiveSpecs(),
                    ActiveGender = session.GetActiveGens(),
                    ActiveTowns = session.GetActiveTowns()
                });
        }

        [HttpPost]
        public RedirectToActionResult Delete()
        {
            // delete favorite teams from session and cookie
            var session = new SMGSession(HttpContext.Session);
            var cookies = new SMGCookies(Response.Cookies);

            session.RemoveMyPhyc();
            cookies.RemoveMyPhycIds();

            // set delete message
            TempData["message"] = "Favorite physicians cleared";

            // redirect to Home page
            return RedirectToAction("Index", "FindaProvider",
                new {
                    ActiveSpecs = session.GetActiveSpecs(),
                    ActiveGens = session.GetActiveGens(),
                    ActiveTowns = session.GetActiveTowns()
                });
        }
    }
}

Controllers/FindaProviderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using SububanMedicalGroupSMGWebApp.Models;
using SububanMedicalGroupSMGWebApp.Models.DataLayer;
using SububanMedicalGroupSMGWebApp.Models.DataLayer.Repositories;
using SububanMedicalGroupSMGWebApp.Models.DomainModels;
using SububanMedicalGroupSMGWebApp.Models.ExtensionMethods;
using SububanMedicalGroupSMGWebApp.Models.Grid;
using SububanMedicalGroupSMGWebApp.Models.ViewModels;

namespace SububanMedicalGroupSMGWebApp.Controllers
{
    public class FindaProviderController : Controller
    {
        private SMGWebAppContext context;
        private List<Speciality> speciality;
        private Repository<Physician> data { get; set; }

        public FindaProviderController(SMGWebAppContext ctx)
        {
            context = ctx;
            speciality = context.Specialities
                .OrderBy(c => c.SpecialityID)
                .ToList();
            data = new Repository<Physician>(ctx);
        }
        //public IActionResult List(string id)
        //{
        //    var filter = new Filters(id);
        //    ViewBag.Filter = filter;
        //    ViewBag.Specialities = context.specialities.ToList();
        //    ViewBag.Clinics = context.Clinics.ToList();
        //    ViewBag.Filterds = Filter.Filterds;

        //    IQueryable<Physician> query = context.physicians.Include(t => t.Speciality).Include(t => t.Clinic);

        //    if (filter.HasSpecialities)
        //    {
        //        query = query.Where(t => t.SpecialitiesID.ToString() == filter.SpecialitiesID);
        //    }

        //    if (filter.HasClinics)
        //    {
        //        query = query.Where(t => t.ClinicID.ToString() == filter.clinicID);
        //    }

        //    if (filter.HasGenders)
        //    {
        //        if (filter.Genders == "Male") query = query.Where(t => t.Gender == filter.Genders);
        //        else if (filter.Genders == "Female") query = query.Where(t => t.Gender == filter.Genders);
        //    }
        //    var physicians = query.OrderBy(t => t.Gender).ToList();
        //    var wbAppViewModel = new WbAppViewModel
        //    {
        //        Physicians = physicians,
        //        Clinics = ViewBag.Clinics,
        //        Specialities = ViewBag.Specialities
        //    };
        //    return View(wbAppViewModel);
        //}
        public ViewResult Index(SMGViewModel model, SMGGridData values)
        {
            string combinedValues = $"{model.ActiveSpecs},{model.ActiveGens},{model.ActiveTowns}";
            string[] filter = combinedValues.Split(',');
            string id = string.Join('-', filter);
            var filters = new Filters(id);
            ViewBag.Filter = filters;
            // store active conference and division in session
            var session = new SMGSession(HttpContext.Session);
            session.SetActiveSpecs(model.ActiveSpecs);
            session.SetActiveGens(model.ActiveGens);
            session.SetActiveTowns(model.ActiveTowns);

            // if no count value in session, use data in cookie
            // to restore fave teams in session 
            int? count = session.GetMyPhycCount();
            if (!count.HasValue)
            {
                var cookies = new SMGCookies(Request.Cookies);
                string[] ids = cookies.GetMyPhycIds();

                if (ids.Length > 0)
                {
                    var myteams = context.Physician
                        .Include(t => t.Clinic)
                        .Include(t => t.Specialities)
                        .Where(t => ids.Contains(t.PhysicianID.ToString()))
                        .ToList();
                    session.SetMyPhyc(myteams);
                }
            }

            // get conferences and divisions from database
            //model.Physicians = context.physicians.ToList();
            //model.Clinics = context.Clinics.ToList();
            //model.Specialities = context.Specialities.ToList();
            ViewBag.GenderFilterValues = Filters.GenderFilterValues;
            var options = new QueryOptions<Physician>
            {
                Includes = "Specialities, Clinic",
                OrderByDirection = values.SortDirection,
                PageNumber = values.PageNumber,
                PageSize = values.PageSize
            };
            if (model.ActiveSorter == "Loc")
            {
                if (values.IsSortByLocation)
                {
                    options.OrderBy = b => b.Clinic.AddressTown;
                    options.OrderByDirection = "asc";
                }
            }
            else if (model.ActiveSorter == "A-Z")
            {
                if (values.IsSortByLastName)
                {
                    options.OrderBy = b => b.LastName;
                    options.OrderByDirection = "asc";
                }
            }
            else if (model.ActiveSorter == "Z-A")
            {
                if (values.IsSortByLastName)
                {
                    options.OrderBy = b => b.LastName;
                    options.OrderByDirection = "desc";

                }
            }
            // get teams from database - filter by conference and division
            //IQueryable<Physician> query = context.physicians.OrderBy(t => t.FirstName);
            IQueryable<Physician> query = context.Physician.Include(t => t.Specialities).Include(t => t.Clinic);
            if (model.ActiveSpecs != "all" && model.ActiveTowns != "all")
            {
                options.Where = t => t.Specialities.SpecialityID.ToString() == model.ActiveSpecs.ToLower() && t.Clinic.ClinicId.ToString() == model.ActiveTowns.ToLower();
            }
            if (model.ActiveSpecs != "all")
            {
                options.Where = t => t.Specialities.SpecialityID.ToString() == model.ActiveSpecs.ToLower();
            }
            if (model.ActiveTowns != "all")
            {
                options.Where = t => t.Clinic.ClinicId.ToString() == model.ActiveTowns.ToLower();
            }

            if (filters.HasGenders)
            {
                options.Where = t => t.Gender == filters.Gender;
            }

            //model.Physicians = query.ToList();
            model.Physicians = query.OrderBy(t => t.Gender).ToList();

            SMGViewModel sMGViewModel = new SMGViewModel
            {
                Physic = data.List(options),
                Clinics = context.Clinics.ToList(),
                Specialities = context.Specialities.ToList(),
                CurrentRoute = values,
                TotalPages = values.GetTotalPages(data.Count),
                ActiveSpecs = model.ActiveSpecs,
                ActiveGens = model.ActiveGens,
                ActiveTowns = model.ActiveTowns,
                ActiveSorter = model.ActiveSorter
            };
            //model.Physicians = query.OrderBy(t => t.Gender).ToList();
            return View(sMGViewModel);
        }
        
        public IActionResult Details(string id)
        {
            var session = new SMGSession(HttpContext.Session);
            var model = new SMGViewModel
            {
                Physician = context.Physician
                    .Include(t => t.Specialities)
                    .Include(t => t.Clinic)
                    //.Include(t => t.Gender)
                    .FirstOrDefault(t => t.PhysicianID.ToString() == id) ?? new Physician(),
                ActiveSpecs = session.GetActiveSpecs(),
                ActiveGens = session.GetActiveGens(),
                ActiveTowns = session.GetActiveTowns()
            };
            return View(model);
        }

    }
}

Views/FindaProvider/Details.cshtml
@model SububanMedicalGroupSMGWebApp.Models.ViewModels.SMGViewModel
@{
    ViewData["Title"] = "Team Details";
}

<h2 class="text-center p-2">Physician Details</h2>

<div class="row">
    <div class="col-6 offset-3">
        <ul class="list-group text-center">
            <li class="list-group-item">
                <img src="~/images/@(Model.Physician.FirstName).png" alt="@Model.Physician.FirstName @Model.Physician.LastName" />
                <h3>@Model.Physician.FirstName @Model.Physician.LastName</h3>
            </li>
            <li class="list-group-item">
                <h4>Speciality: @Model.Physician.Specialities.Specialities</h4>
            </li>
            <li class="list-group-item">
                <h4>AddressTown: @Model.Physician.Clinic.AddressTown</h4>
            </li>
            <li class="list-group-item">
                <form asp-action="Add" asp-controller="Favorites" method="post">
                    <a asp-action="Index" asp-controller="FindaProvider" class="btn btn-primary"
                       asp-route-activeSpecs="@Model.ActiveSpecs"
                       asp-route-activeGens="@Model.ActiveGens"
                       asp-route-activeTowns="@Model.ActiveTowns">Return to Home Page</a>
                    <button type="submit" class="btn btn-primary">
                        Add to Favorites
                    </button>
                    <input type="hidden" asp-for="Physician.PhysicianID" />
                </form>
            </li>
        </ul>
    </div>
</div>

Views/FindaProvider/Index.cshtml
@using SububanMedicalGroupSMGWebApp.Models.DomainModels;
@using SububanMedicalGroupSMGWebApp.Models.Grid;
@model SububanMedicalGroupSMGWebApp.Models.ViewModels.SMGViewModel
@{
    ViewData["Title"] = "Physicians List";
    SMGGridData current = Model.CurrentRoute;
    GridData routes = Model.CurrentRoute.Clone();
}
@if (@TempData["PhysicianMessage"] != null)
{
    <div style="margin-top:8em; background: green">
        <h4>@TempData["PhysicianMessage"]</h4>
    </div>
}
<h1>@ViewBag.Title</h1>
<div class="row">
@*    <div class="col-md-3" >
        <h3 class="mt-3">Specialities</h3>
        <div class="list-group">
            <a asp-action="Index"
               asp-route-activeSpecs="all"
               asp-route-activeGens="@Model.ActiveGens"
               asp-route-activeTowns="@Model.ActiveTowns"
               class="list-group-item @Model.CheckActiveSpecs("all")">
                All
            </a>
            @foreach (SububanMedicalGroupSMGWebApp.Models.DomainModels.Speciality spec in Model.Specialities)
            {
                <a asp-action="Index"
               asp-route-activeSpecs="@spec.SpecialityID"
               asp-route-activeTowns="@Model.ActiveTowns"
               asp-route-activeGens="@Model.ActiveGens"
                   class="list-group-item @Model.CheckActiveSpecs(spec.SpecialityID.ToString())">
                    @spec.Specialities
                </a>
            }
        </div>
        <h3 class="mt-3">Towns of Clinic</h3>
        <div class="list-group">
            <a asp-action="Index"
               asp-route-activeTowns="all"
               asp-route-activeSpecs="@Model.ActiveSpecs"
               asp-route-activeGens="@Model.ActiveGens"
               class="list-group-item @Model.CheckActiveTowns("all")">
                All
            </a>
            @foreach (SububanMedicalGroupSMGWebApp.Models.DomainModels.Clinic conf in Model.Clinics)
            {
                <a asp-action="Index"
               asp-route-activeTowns="@conf.ClinicId"
               asp-route-activeSpecs="@Model.ActiveSpecs"
               asp-route-activeGens="@Model.ActiveGens"
                   class="list-group-item @Model.CheckActiveTowns(conf.ClinicId.ToString())">
                    @conf.AddressTown
                </a>
            }
        </div>
        <h3 class="mt-3">Gender</h3>
        <div class="list-group">
            <a asp-action="Index"
               asp-route-activeGens="all"
               asp-route-activeTowns="@Model.ActiveTowns"
               asp-route-activeSpecs="@Model.ActiveSpecs"
               class="list-group-item @Model.CheckActiveGens("all")">
                All
            </a>
            @foreach (var Gens in ViewBag.GenderFilterValues)
            {
                <a asp-action="Index"
               asp-route-activeGens="@Gens.Key"
               asp-route-activeSpecs="@Model.ActiveSpecs"
               asp-route-activeTowns="@Model.ActiveTowns"
                   class="list-group-item @Model.CheckActiveGens(Gens.Key)">
                    @Gens.Value
                </a>
            }
        </div>
    </div>
*@
    <div class="col-md-3">
        <form asp-action="Index" asp-controller="FindaProvider" method="get">
        <h3 class="mt-3">Specialities</h3>
            <div class="list-group">
                <select name="activeSpecs" class="form-control">
                    <option value="all" class="@Model.CheckActiveSpecs("all")">All</option>
                    @foreach (SububanMedicalGroupSMGWebApp.Models.DomainModels.Speciality Spec in Model.Specialities)
                    {
                        if (Model.ActiveSpecs == Spec.SpecialityID.ToString())
                        {
                            <option value="@Spec.SpecialityID" selected="true" class="@Model.CheckActiveSpecs(Spec.SpecialityID.ToString())">
                                @Spec.Specialities
                            </option>
                        }
                        else
                        {
                            <option value="@Spec.SpecialityID" class="@Model.CheckActiveSpecs(Spec.SpecialityID.ToString())">
                                @Spec.Specialities
                            </option>
                        }

                    }
                </select>
            </div>
            <h3 class="mt-3">Clinic Towns</h3>
            <div class="list-group">
                <select name="activeTowns" class="form-control">
                    <option value="all" class="@Model.CheckActiveTowns("all")">All</option>
                    @foreach (SububanMedicalGroupSMGWebApp.Models.DomainModels.Clinic CL in Model.Clinics)
                    {
                        if (Model.ActiveTowns == CL.ClinicId.ToString())
                        {
                            <option value="@CL.ClinicId" selected="true" class="@Model.CheckActiveTowns(@CL.ClinicId.ToString())">
                                @CL.AddressTown
                            </option>
                        }
                        else
                        {
                            <option value="@CL.ClinicId" class="@Model.CheckActiveTowns(@CL.ClinicId.ToString())">
                                @CL.AddressTown
                            </option>
                        }

                    }
                </select>
            </div>
            <h3 class="mt-3">Gender</h3>
            <div class="list-group">
                <select name="activeGens" class="form-control">
                    <option value="all" class="@Model.CheckActiveGens("all")">All</option>
                    @foreach (var GD in ViewBag.GenderFilterValues)
                    {
                        if (Model.ActiveGens == GD.Key)
                        {
                            <option value="@GD.Key" selected="true" class="@Model.CheckActiveGens(GD.Key)">
                                @GD.Value
                            </option>
                        }
                        else
                        {
                            <option value="@GD.Key" class="@Model.CheckActiveGens(GD.Key)">
                                @GD.Value
                            </option>
                        }
                    }
                </select>
            </div>
            <h3 class="mt-3">Sort options</h3>
            <div class="list-group">
                <select name="activeSorter" class="form-control">
                    <option value="Loc">Location</option>
                    <option value="A-Z">Last Name (A-Z)</option>
                    <option value="Z-A">Last Name (Z-A)</option>
                </select>
            </div>
            <button class="btn btn-primary" type="submit">Apply Filters</button>
            <a asp-action="Index" asp-route-id="" class="btn btn-primary">Clear</a>
        </form>
    </div>




    <div class="col-md-9">
    <div class="container mt-5">
            <div class="row">
                @foreach (SububanMedicalGroupSMGWebApp.Models.DomainModels.Physician physician in Model.Physic)
                {
                    <div class="col-md-4 mb-4" style="background:powderblue">
                        <a asp-action="Details" asp-route-id="@physician.PhysicianID">
                            <img src="~/images/@(physician.FirstName).png" alt="@physician.FirstName @physician.LastName" class="card-img-top img-fluid" />
                        </a>
                        <a asp-action="Details" asp-route-id="@physician.PhysicianID">
                            <h5 class="card-title">@physician.FirstName &nbsp; @physician.LastName</h5>
                        </a>
                        <h5>@physician.FirstName @physician.LastName</h5>
                        <p>@physician.Specialities.Specialities</p>
                        <p>@physician.Clinic.AddressTown</p>
                        <a asp-action="Details" class="btn btn-primary" asp-route-id="@physician.PhysicianID">Details</a>
                    </div>
                }
            </div>
    </div>
        @{
            routes = current.Clone();

            for (int i = 1; i <= Model.TotalPages; i++)
            {
                routes.PageNumber = i;
                string active = @Nav.Active(i, current.PageNumber);
                <a asp-action="Index" asp-all-route-data="@routes.ToDictionary()"
               class="btn btn-outline-primary @active" style="border:#0d6efd !important;">@i</a>
            }
        }
    </div>


</div>